# Generated by Django 2.0.13 on 2019-02-14 05:07

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('apidemo', '0008_auto_20190211_1249'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='profile',
            name='user',
        ),
        migrations.AlterField(
            model_name='photo',
            name='file',
            field=models.ImageField(upload_to='', validators=[django.core.validators.FileExtensionValidator(allowed_extensions=['jpeg'])]),
        ),
        migrations.DeleteModel(
            name='Profile',
        ),
    ]
