# Generated by Django 2.0.13 on 2019-02-15 10:01

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('apidemo', '0009_auto_20190214_0507'),
    ]

    operations = [
        migrations.CreateModel(
            name='Notes',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(default=None, max_length=150)),
                ('description', models.TextField()),
                ('created_time', models.DateTimeField(auto_now_add=True, null=True)),
                ('remainder', models.DateTimeField(blank=True, default=None, null=True)),
                ('is_archived', models.BooleanField(default=False)),
                ('is_deleted', models.BooleanField(default=False)),
                ('color', models.CharField(blank=True, default=None, max_length=50, null=True)),
                ('image', models.ImageField(default=None, null=True, upload_to='')),
                ('trash', models.BooleanField(default=False)),
                ('is_pinned', models.NullBooleanField(default=None)),
                ('label', models.CharField(default=None, max_length=50)),
                ('collaborate', models.ManyToManyField(blank=True, null=True, related_name='collaborated_user', to=settings.AUTH_USER_MODEL)),
                ('user', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='owner', to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
