# Generated by Django 2.0.13 on 2019-02-15 10:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('apidemo', '0010_notes'),
    ]

    operations = [
        migrations.AlterField(
            model_name='notes',
            name='label',
            field=models.CharField(default=None, max_length=50, null=True),
        ),
    ]
