# Generated by Django 2.0.13 on 2019-02-15 11:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('apidemo', '0011_auto_20190215_1009'),
    ]

    operations = [
        migrations.AlterField(
            model_name='notes',
            name='remainder',
            field=models.CharField(default=None, max_length=25, null=True),
        ),
    ]
