# Generated by Django 2.0.13 on 2019-02-20 04:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('apidemo', '0012_auto_20190215_1107'),
    ]

    operations = [
        migrations.AlterField(
            model_name='notes',
            name='description',
            field=models.TextField(null=True),
        ),
        migrations.AlterField(
            model_name='notes',
            name='title',
            field=models.CharField(default=None, max_length=150, null=True),
        ),
    ]
