# Generated by Django 2.0.13 on 2019-02-20 04:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('apidemo', '0013_auto_20190220_0451'),
    ]

    operations = [
        migrations.AlterField(
            model_name='notes',
            name='description',
            field=models.TextField(),
        ),
        migrations.AlterField(
            model_name='notes',
            name='title',
            field=models.CharField(default=None, max_length=150),
        ),
    ]
