# Generated by Django 2.0.13 on 2019-02-22 05:44

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('apidemo', '0014_auto_20190220_0453'),
    ]

    operations = [
        migrations.RenameField(
            model_name='notes',
            old_name='remainder',
            new_name='reminder',
        ),
    ]
