# Generated by Django 2.0.13 on 2019-02-22 10:16

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('apidemo', '0015_auto_20190222_0544'),
    ]

    operations = [
        migrations.RenameField(
            model_name='notes',
            old_name='color',
            new_name='for_color',
        ),
    ]
