# Generated by Django 2.0.13 on 2019-02-27 04:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('apidemo', '0016_auto_20190222_1016'),
    ]

    operations = [
        migrations.CreateModel(
            name='Labels',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('label_name', models.CharField(max_length=50)),
                ('created_time', models.DateTimeField(auto_now_add=True, null=True)),
            ],
        ),
    ]
