# Generated by Django 2.0.13 on 2019-03-04 05:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('apidemo', '0019_map_labels'),
    ]

    operations = [
        migrations.AlterField(
            model_name='notes',
            name='reminder',
            field=models.DateTimeField(default=None, null=True),
        ),
    ]
