# Generated by Django 2.0.13 on 2019-03-04 05:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('apidemo', '0020_auto_20190304_0521'),
    ]

    operations = [
        migrations.AlterField(
            model_name='notes',
            name='reminder',
            field=models.CharField(default=None, max_length=25, null=True),
        ),
    ]
