# Generated by Django 2.0.13 on 2019-03-04 05:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('apidemo', '0022_auto_20190304_0543'),
    ]

    operations = [
        migrations.AlterField(
            model_name='notes',
            name='reminder',
            field=models.DateField(default=None, null=True),
        ),
    ]
