# Generated by Django 2.0.13 on 2019-03-08 06:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('apidemo', '0025_auto_20190304_0604'),
    ]

    operations = [
        migrations.AddField(
            model_name='notes',
            name='archive_time',
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
