# Generated by Django 2.0.13 on 2019-03-08 07:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('apidemo', '0026_notes_archive_time'),
    ]

    operations = [
        migrations.AddField(
            model_name='notes',
            name='trash_time',
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
